In [12]:
# Program to multiply two matrices using nested loops

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [4]:
# Program to multiply two matrices

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]
# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]
# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
   for j in range(len(Y[0])):
       # iterate through rows of Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [5]:
# Program to multiply two matrices using list comprehension

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*Y)] for X_row in X]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [6]:
# 3x3 matrix
X = [[12,0,3],
    [0 ,5,13],
    [4 ,0,9]]
# 3x1 matrix
Y = [[11,10,0],
    [0,8,0],
    [0,0,7]]
# result is 3x1
result = [[0,0,0],
         [0,0,0],
         [0,0,0]]

In [7]:
# 3x3 matrix
X = [[12,0,3],
    [0 ,5,3],
    [4 ,0,9]]
# 3x1 matrix
Y = [5,6,4]
# result is 3x1
result = [0,0,0]

In [8]:
X

[[12, 0, 3], [0, 5, 3], [4, 0, 9]]

In [9]:
Y

[5, 6, 4]

In [10]:
result

[0, 0, 0]

In [11]:
# iterate through rows of X
for i in range(len(X)):
   # iterate through columns of Y
    # iterate through rows of Y
    for k in range(len(Y)):
        result[i] += X[i][k] * Y[k]

for r in result:
   print(r)

72
42
56


In [221]:
# 3x3 matrix
X = [[12,0,3],
    [0 ,5,13],
    [4 ,0,9]]
# 3x1 matrix
Y = [0,0,7]
# result is 3x1
result = [0,0,0]

In [248]:
import scipy.sparse as sparse

def randomsparse(r,c):
    return sparse.random(r, c, density=0.50)

X=randomsparse(3,3)
Y=randomsparse(1,3)

X = [[12,0,3],
    [0 ,5,13],
    [4 ,0,9]]

Y = [0,0,7]

result = [0,0,0]




def sparse(X,Y):
    # iterate through rows of X
    valueslist=[]
    columnnumber=[]
    rownumber=[]
    valuesdictX={}
    valuesdictY={}
    for i in range(len(X)):

        for k in range(len(Y)):
            if not(X[i][k]==0 or Y[k]==0):
                valueslist.append(X[i][k])
                columnnumber.append(k)
                rownumber.append(i)
    rownumber.append(rownumber[-1])
    rowend=[]
    rowend.append(0)
    for b in range(0,len(rownumber)-1):  
        if not(rownumber[b]==rownumber[b+1]):
            rowend.append(rownumber.index(rownumber[b+1]))

    columnvalues=[]
    for i in columnnumber:
        columnvalues.append(Y[i])
    columnvalues
    mutiply=zip(valueslist,columnvalues)
    multiplylist=[]
    for i,j in mutiply:
        multiplylist.append(i*j)
    multiplylist
    rowend.append(len(multiplylist))
    dot=[]
    for i in range(0,len(rowend)-1):
        dot.append(sum(multiplylist[rowend[i]:rowend[i+1]]))

    return dot                    
    
sparse(X,Y)

[21, 91, 63]

In [240]:
sparse(X,Y)

[21, 91, 63]

In [261]:
import scipy.sparse as sparse

def randomsparse(r,c):
    return sparse.random(r, c, density=0.50)

X=randomsparse(3,3)
Y=randomsparse(3,3)
print(X)
print(Y)

  (2, 0)	0.6773460729061089
  (1, 2)	0.39093416634343203
  (2, 1)	0.8994604290936814
  (0, 1)	0.017675835056707778
  (0, 1)	0.4270936945337961
  (2, 0)	0.12129308738720801
  (1, 1)	0.21446876920966085
  (1, 2)	0.7103790088065355


In [259]:
import scipy.sparse as sparse

def randomsparse(r,c):
    return sparse.random(r, c, density=0.50)

X=randomsparse(3,3)
Y=randomsparse(3,3)

def sparse1(X,Y):
    # iterate through rows of X
    valueslist=[]
    columnnumber=[]
    rownumber=[]
    valuesdictX={}
    valuesdictY={}
    for i in range(len(X)):
        for j in range(len(Y[0]))
            for k in range(len(Y)):
                if not(X[i][k]==0 or Y[k]==0):
                    valueslist.append(X[i][k])
                    columnnumber.append(k)
                    rownumber.append(i)
                #valuesdictX[i,k]=X[i][k]
                #valuesdictY[k,j]=Y[k][j]
                #result[i][j] += X[i][k] * Y[k]
    rownumber.append(rownumber[-1])
    rowend=[]
    rowend.append(0)
    for b in range(0,len(rownumber)-1):  
        if not(rownumber[b]==rownumber[b+1]):
            rowend.append(rownumber.index(rownumber[b+1]))

    columnvalues=[]
    for i in columnnumber:
        columnvalues.append(Y[i])
    columnvalues
    mutiply=zip(valueslist,columnvalues)
    multiplylist=[]
    for i,j in mutiply:
        multiplylist.append(i*j)
    multiplylist
    rowend.append(len(multiplylist))
    dot=[]
    for i in range(0,len(rowend)-1):
        dot.append(sum(multiplylist[rowend[i]:rowend[i+1]]))

    return dot                    
    
#for r in result:
#    print(r)

SyntaxError: invalid syntax (<ipython-input-259-52ea41daffae>, line 17)

In [257]:
Y.toarray()

array([[0.        , 0.6531297 , 0.47139601],
       [0.67419104, 0.08610175, 0.        ],
       [0.        , 0.        , 0.        ]])

In [258]:
sparse1(X.toarray(),Y.toarray())

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [153]:
def get_item(row_index, column_index, matrix):
    # Get row values
    row_start = matrix.indptr[row_index]
    row_end = matrix.indptr[row_index + 1]
    row_values = matrix.data[row_start:row_end]

    # Get column indices of occupied values
    index_start = matrix.indptr[row_index]
    index_end = matrix.indptr[row_index + 1]

    # contains indices of occupied cells at a specific row
    row_indices = list(matrix.indices[index_start:index_end])

    # Find a positional index for a specific column index
    value_index = row_indices.index(column_index)

    if value_index >= 0:
        return row_values[value_index]
    else:
        # non-zero value is not found
        return 0

In [164]:
# import sparse 
import scipy.sparse as sparse
# import stats
import scipy.stats as stats
# import numpy
import numpy as np


# Convert the sparse matrix to a full matrix


In [165]:
A = sparse.random(5, 5, density=0.25)

In [168]:
A.toarray()

array([[0.        , 0.22327296, 0.        , 0.        , 0.67020674],
       [0.        , 0.        , 0.        , 0.        , 0.38070845],
       [0.21496611, 0.6951946 , 0.        , 0.        , 0.23984014],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

In [169]:
print(A)

  (0, 4)	0.6702067418556428
  (2, 0)	0.21496611382996045
  (2, 4)	0.23984013884667288
  (2, 1)	0.6951946011729817
  (1, 4)	0.38070845481486904
  (0, 1)	0.22327295734416153


In [ ]:
import scipy.stats as stats
import numpy as np

In [267]:
import scipy.sparse as sparse

def randomsparse(r,c):
    return sparse.random(r, c, density=0.50)

A=randomsparse(3,3)
B=randomsparse(3,3)
print(A)


  (1, 0)	0.2213559748001186
  (2, 0)	0.16015561159358738
  (0, 1)	0.5946509875119824
  (2, 1)	0.2786444112080617


In [206]:
print(B)

  (2, 2)	0.3404212156467792
  (0, 2)	0.9889731242234964
  (1, 1)	0.7326818489190329
  (1, 2)	0.5103330626946722


In [207]:
print(A.toarray())

[[0.02090933 0.15011222 0.81447221]
 [0.         0.99895188 0.        ]
 [0.         0.         0.        ]]


In [208]:
print(B.toarray())

[[0.         0.         0.98897312]
 [0.         0.73268185 0.51033306]
 [0.         0.         0.34042122]]


In [209]:
dictmain={}
B.split()

AttributeError: split not found

In [155]:
get_item(0, 3, X)

AttributeError: 'list' object has no attribute 'indptr'

In [264]:
valuesdictX

{(0, 0): 12,
 (0, 1): 7,
 (0, 2): 3,
 (1, 0): 4,
 (1, 1): 5,
 (1, 2): 6,
 (2, 0): 7,
 (2, 1): 8,
 (2, 2): 9}

In [149]:
valuesdictY

{(0, 0): 5,
 (1, 0): 6,
 (2, 0): 4,
 (0, 1): 8,
 (1, 1): 7,
 (2, 1): 5,
 (0, 2): 1,
 (1, 2): 3,
 (2, 2): 9,
 (0, 3): 2,
 (2, 3): 1}

In [152]:
for i,j in valuesdictX.keys():
    for k,l in valuesdictY.keys():
        if i==l:
            print(i,j,l)

0 0 0
0 0 0
0 0 0
0 1 0
0 1 0
0 1 0
0 2 0
0 2 0
0 2 0
1 0 1
1 0 1
1 0 1
1 1 1
1 1 1
1 1 1
1 2 1
1 2 1
1 2 1
2 0 2
2 0 2
2 0 2
2 1 2
2 1 2
2 1 2
2 2 2
2 2 2
2 2 2


In [59]:
valueslist

[12, 3, 5, 3, 4, 9]

In [60]:
columnnumber

[0, 2, 1, 2, 0, 2]

In [61]:
rownumber.append(rownumber[-1])

In [62]:
rownumber

[0, 0, 1, 1, 2, 2, 2]

In [63]:
rownumber[0]

0

In [64]:
rownumber.append(rownumber[-1])
rowend=[]
rowend.append(0)
for b in range(0,len(rownumber)-1):  
    if not(rownumber[b]==rownumber[b+1]):
        rowend.append(rownumber.index(rownumber[b+1]))
        

In [65]:
rowend

[0, 2, 4]

In [66]:
for i in columnnumber:
    print (i)

0
2
1
2
0
2


In [67]:
valueslist

[12, 3, 5, 3, 4, 9]

In [71]:
for i in Y:
    print(i)

5
6
4


In [72]:
rownumber.append(rownumber[-1])
rowend=[]
rowend.append(0)
for b in range(0,len(rownumber)-1):  
    if not(rownumber[b]==rownumber[b+1]):
        rowend.append(rownumber.index(rownumber[b+1]))
        
columnvalues=[]
for i in columnnumber:
    columnvalues.append(Y[i])
columnvalues
mutiply=zip(valueslist,columnvalues)
multiplylist=[]
for i,j in mutiply:
    multiplylist.append(i*j)
multiplylist
rowend.append(len(multiplylist))
dot=[]
for i in range(0,len(rowend)-1):
    dot.append(sum(multiplylist[rowend[i]:rowend[i+1]]))
    
return dot

[5, 4, 6, 4, 5, 4]

In [81]:
mutiply=zip(valueslist,columnvalues)

In [82]:
multiplylist=[]
for i,j in mutiply:
    multiplylist.append(i*j)
multiplylist

[60, 12, 30, 12, 20, 36]

In [84]:
rowend.append(len(multiplylist))

In [85]:
rowend

[0, 2, 4, 6]

In [91]:
dot=[]
for i in range(0,len(rowend)-1):
    dot.append(sum(multiplylist[rowend[i]:rowend[i+1]]))

In [92]:
dot

[72, 42, 56]

In [263]:
Amys

NameError: name 'Amys' is not defined

In [13]:
def getval(A,key):
    if key in A:
        return A[key]
    else:
        return 0
getval(valuesdictX,(1,1))

NameError: name 'valuesdictX' is not defined

In [268]:
dir(sparse)

['SparseEfficiencyWarning',
 'SparseWarning',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_csparsetools',
 '_index',
 '_matrix_io',
 '_sparsetools',
 '_warnings',
 'absolute_import',
 'base',
 'block_diag',
 'bmat',
 'bsr',
 'bsr_matrix',
 'compressed',
 'construct',
 'coo',
 'coo_matrix',
 'csc',
 'csc_matrix',
 'csgraph',
 'csr',
 'csr_matrix',
 'data',
 'dia',
 'dia_matrix',
 'diags',
 'division',
 'dok',
 'dok_matrix',
 'extract',
 'eye',
 'find',
 'hstack',
 'identity',
 'issparse',
 'isspmatrix',
 'isspmatrix_bsr',
 'isspmatrix_coo',
 'isspmatrix_csc',
 'isspmatrix_csr',
 'isspmatrix_dia',
 'isspmatrix_dok',
 'isspmatrix_lil',
 'kron',
 'kronsum',
 'lil',
 'lil_matrix',
 'linalg',
 'load_npz',
 'print_function',
 'rand',
 'random',
 'save_npz',
 'spdiags',
 'spmatrix',
 'sputils',
 'test',
 'tril',
 'triu',
 'vstack']

In [270]:
import numpy

In [271]:
numpy.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [275]:
A[3,8]=0.5
np.linalg.inv(A)

TypeError: 'coo_matrix' object does not support item assignment

In [14]:
from scipy.sparse.linalg import inv
from scipy.sparse import csr_matrix
As=csr_matrix(A)

(inv(As)).toarray()


NameError: name 'A' is not defined

In [280]:
from sklearn.datasets import load_boston
boston = load_boston()
print(dir(boston))
print(boston.data.shape)
print(boston.feature_names)
print(boston.DESCR)

['DESCR', 'data', 'feature_names', 'filename', 'target']
(506, 13)
['CRIM' 'ZN' 'INDUS' 'CHAS' 'NOX' 'RM' 'AGE' 'DIS' 'RAD' 'TAX' 'PTRATIO'
 'B' 'LSTAT']
.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employm

Norms

In [15]:
import numpy as np
v=[1,2,10,-20]

np.power(sum(np.power(np.abs(np.array(v)),2)),1/2)

22.47220505424423

In [21]:
np.power(np.abs(np.array(v)),2)

array([  1,   4, 100, 400], dtype=int32)

    zero norm is the number of non zero elements cardinality

In [288]:
a=[1,3,1,-4]

In [289]:
b=[2,0,1,-2]

In [295]:
np.power(sum(np.power(np.abs(np.array(a)),2)),1/2)

5.196152422706632

In [296]:
np.power(sum(np.power(np.abs(np.array(b)),2)),1/2)

3.0

In [294]:
np.power(sum(np.power(np.abs(np.array(a)),np.amax(a))),1/np.amax(a))

4.530654896083492

In [293]:
np.amax(a)

3

In [ ]:
np.power(sum(np.power(np.abs(np.array(a)),np.amax(a))),1/np.amax(a))

In [301]:
for p in range(1,10):
    print(p,np.power(sum(np.power(np.abs(np.array(a)),p),1/p)))

ValueError: invalid number of arguments

norm is like a vector(distance between two vectors) and distance is distance bw two points
d(u,v)=||u - v||
dot product is big
difference in distance is small

In [302]:
a=[1,2,3,4,5]

In [303]:
b=[2,3,5,7,8]

In [305]:
c=a+b

In [307]:
d=set(c)

In [310]:
e=list(d)

In [311]:
e.sort()

In [312]:
e

[1, 2, 3, 4, 5, 7, 8]

In [314]:
e.split(',')

AttributeError: 'list' object has no attribute 'split'